/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerCriacaoMalha;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lucas de Liz, Matheus Maas
 */
public class MenuMalha extends javax.swing.JFrame {

    private SimuladorMalha viewSimuladorMalha;
    private ControllerCriacaoMalha criarMalha;

    /**
     * Creates new form viewMenuMalha
     */
    public MenuMalha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonMalha1 = new javax.swing.JButton();
        jButtonMalha2 = new javax.swing.JButton();
        jButtonMalha3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setText("Clique na Malha Que Deseja Simular");

        jButtonMalha1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonMalha1.setText("Malha 1");
        jButtonMalha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMalha1ActionPerformed(evt);
            }
        });

        jButtonMalha2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonMalha2.setText("Malha 2");
        jButtonMalha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMalha2ActionPerformed(evt);
            }
        });

        jButtonMalha3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonMalha3.setText("Malha 3");
        jButtonMalha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMalha3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMalha1)
                    .addComponent(jButtonMalha2)
                    .addComponent(jButtonMalha3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelTitulo)
                .addGap(65, 65, 65)
                .addComponent(jButtonMalha1)
                .addGap(40, 40, 40)
                .addComponent(jButtonMalha2)
                .addGap(40, 40, 40)
                .addComponent(jButtonMalha3)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMalha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMalha1ActionPerformed
        this.setVisible(false);
        criarMalha = ControllerCriacaoMalha.getInstance();
        try {
            criarMalha.setCaminhoMalha("src/exemplosMalhas/malha-exemplo-1.txt");
            viewSimuladorMalha = new SimuladorMalha();
            viewSimuladorMalha.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MenuMalha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMalha1ActionPerformed

    private void jButtonMalha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMalha2ActionPerformed
        this.setVisible(false);
        criarMalha = ControllerCriacaoMalha.getInstance();
        try {
            criarMalha.setCaminhoMalha("src/exemplosMalhas/malha-exemplo-2.txt");
            viewSimuladorMalha = new SimuladorMalha();
            viewSimuladorMalha.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MenuMalha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMalha2ActionPerformed

    private void jButtonMalha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMalha3ActionPerformed
        this.setVisible(false);
        criarMalha = ControllerCriacaoMalha.getInstance();
        try {
            criarMalha.setCaminhoMalha("src/exemplosMalhas/malha-exemplo-3.txt");
            viewSimuladorMalha = new SimuladorMalha();
            viewSimuladorMalha.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MenuMalha.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMalha3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMalha1;
    private javax.swing.JButton jButtonMalha2;
    private javax.swing.JButton jButtonMalha3;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
