package view;

import controller.ControllerCarro;
import controller.ControllerMalha;
import controller.ControllerEstrada;
import controllerObserver.InterfaceMalha;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import model.MalhaViaria;
import utils.TableCellRendererImage;

/**
 *
 * @author Lucas de Liz, Matheus Maas
 */
public class SimuladorMalha extends javax.swing.JFrame implements InterfaceMalha {

    private static SimuladorMalha instance = null;
    private static MalhaViaria malhaViaria = MalhaViaria.getInstance();
    private static ControllerMalha controllerMalha = controllerMalha = new ControllerMalha();
    private final static ControllerEstrada conEstrada = null;
    private static ControllerCarro conCarro = new ControllerCarro();
    private final ImageIcon areia = new ImageIcon("./imagens/areia.png");
    private final ImageIcon asfalto = new ImageIcon("./imagens/asfalto.png");
    private final ImageIcon setaDireita = new ImageIcon("./imagens/direita.png");
    private final ImageIcon setaEsquerda = new ImageIcon("./imagens/esquerda.png");
    private final ImageIcon setaCima = new ImageIcon("./imagens/cima.png");
    private final ImageIcon setaBaixo = new ImageIcon("./imagens/baixo.png");
    private final ImageIcon carroVerDireita = new ImageIcon("./imagens/carrovermelhodireita.png");
    private final ImageIcon carroVerEsquerda = new ImageIcon("./imagens/carrovermelhoesquerda.png");
    private final ImageIcon carroVerBaixo = new ImageIcon("./imagens/carrovermelhobaixo.png");
    private final ImageIcon carroVerCima = new ImageIcon("./imagens/carrovermelhocima.png");
    private final ImageIcon carroAzuDireita = new ImageIcon("./imagens/carroazuldireita.png");
    private final ImageIcon carroAzuEsquerda = new ImageIcon("./imagens/carroazulesquerda.png");
    private final ImageIcon carroAzuBaixo = new ImageIcon("./imagens/carroazulbaixo.png");
    private final ImageIcon carroAzuCima = new ImageIcon("./imagens/carroazulcima.png");
    private final ImageIcon carroAmaDireita = new ImageIcon("./imagens/carroamarelodireita.png");
    private final ImageIcon carroAmaEsquerda = new ImageIcon("./imagens/carroamareloesquerdo.png");
    private final ImageIcon carroAmaBaixo = new ImageIcon("./imagens/carroamarelobaixo.png");
    private final ImageIcon carroAmaCima = new ImageIcon("./imagens/carroamarelocima.png");
    private static Boolean criarMapa;
    private static int codCarro;

    /**
     * Creates new form viewSimuladorMalha
     *
     * @return
     */
    public static SimuladorMalha getInstance() {
        if (instance == null) {
            instance = new SimuladorMalha();
            conCarro = new ControllerCarro();
        }
        return instance;
    }

    private SimuladorMalha() {

        initComponents();
        malhaViaria = MalhaViaria.getInstance();
        controllerMalha.adicionarObserver(this);
        //gerarTabelaMalha(malhaViaria.getMatriz(), malhaViaria.getLinha(), 
        //malhaViaria.getColuna());
        controllerMalha.gerarMapa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonEncerrar = new javax.swing.JButton();
        jTextFieldQtdMaxima = new javax.swing.JTextField();
        jLabelQtdMaxima = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jTableMalha = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Trânsito");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonEncerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEncerrar.setText("Encerrar");
        jButtonEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncerrarActionPerformed(evt);
            }
        });

        jLabelQtdMaxima.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelQtdMaxima.setText("Quantidade Máxima de Carros:");

        jButtonIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelQtdMaxima)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQtdMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButtonIniciar)
                .addGap(15, 15, 15)
                .addComponent(jButtonVoltar)
                .addGap(15, 15, 15)
                .addComponent(jButtonEncerrar)
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQtdMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQtdMaxima)
                    .addComponent(jButtonVoltar)
                    .addComponent(jButtonEncerrar)
                    .addComponent(jButtonIniciar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableMalha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableMalha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMalha.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableMalha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableMalha.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTableMalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTableMalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonEncerrarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        this.setVisible(false);
        instance = null;
        this.dispose();
        conCarro.interrupt();
        conCarro = null;
        criarMapa = true;
        MenuMalha.getInstance().setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        if (!jTextFieldQtdMaxima.getText().matches("^[0-9]*$")) {
            JOptionPane.showMessageDialog(rootPane, "Somente Números Inteiros!");
            jTextFieldQtdMaxima.setText("");
        } else if ((jTextFieldQtdMaxima.getText().isEmpty())) {
            JOptionPane.showMessageDialog(rootPane, "Por Favor, Preencha o Campo com um Número Inteiro!");
        } else {
            jTextFieldQtdMaxima.setEditable(false);
            this.jButtonIniciar.setEnabled(false);
            try {
                conCarro.criarCarro(Integer.parseInt(jTextFieldQtdMaxima.getText()));

            } catch (InterruptedException ex) {
                Logger.getLogger(SimuladorMalha.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    @Override
    public void gerarTabelaMalha(int[][] matriz, int linha, int coluna) {
        criarMapa = true;

        DefaultTableModel tipoTabela;
        tipoTabela = new DefaultTableModel() {

            @Override
            public int getRowCount() {
                return malhaViaria.getLinha();
            }

            @Override
            public int getColumnCount() {
                return malhaViaria.getColuna();
            }

            @Override
            public Object getValueAt(int Filai, int colunaI) {
                try {
                    if (criarMapa == true) {
                        return colocarIcon(Filai, colunaI, matriz);
                    } else if (criarMapa != true) {
                        return colocarIcon(Filai, colunaI, matriz, codCarro);
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.toString());
                    return null;
                }
                return null;
            }
        };

        tipoTabela.setRowCount(linha);
        tipoTabela.setColumnCount(coluna);
        jTableMalha.setIntercellSpacing(new Dimension(0, 0));
        jTableMalha.setRowHeight(30);
        jTableMalha.setModel(tipoTabela);
        jTableMalha.setDefaultRenderer(Object.class, new TableCellRendererImage());
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();

        for (int i = 0; i < jTableMalha.getColumnModel().getColumnCount(); i++) {
            TableColumn column = jTableMalha.getColumnModel().getColumn(i);
            column.setHeaderRenderer(renderer);
            column.setPreferredWidth(30);
        }

    }

    public ImageIcon colocarIcon(int linha, int coluna, int matriz[][]) {
        if (matriz[linha][coluna] == 0) {
            return areia;
        } else if (matriz[linha][coluna] == 5 || matriz[linha][coluna] == 6 || matriz[linha][coluna] == 7 || matriz[linha][coluna] == 8
                || matriz[linha][coluna] == 9 || matriz[linha][coluna] == 10 || matriz[linha][coluna] == 11 || matriz[linha][coluna] == 12) {
            return asfalto;
        } else if (matriz[linha][coluna] == 1) {
            return setaCima;
        } else if (matriz[linha][coluna] == 2) {
            return setaDireita;
        } else if (matriz[linha][coluna] == 3) {
            return setaBaixo;
        } else if (matriz[linha][coluna] == 4) {
            return setaEsquerda;
        } //else if (matriz[linha][coluna] == 20) {
        // return carroVerDireita;
        // }

        return null;
    }

    public ImageIcon colocarIcon(int linha, int coluna, int matriz[][], int posicao) {

        if (matriz[linha][coluna] == 0) {
            return areia;
        } else if (matriz[linha][coluna] == 5 || matriz[linha][coluna] == 6 || matriz[linha][coluna] == 7 || matriz[linha][coluna] == 8
                || matriz[linha][coluna] == 9 || matriz[linha][coluna] == 10 || matriz[linha][coluna] == 11 || matriz[linha][coluna] == 12) {
            return asfalto;
        } else if (matriz[linha][coluna] == 1) {
            return setaCima;
        } else if (matriz[linha][coluna] == 2) {
            return setaDireita;
        } else if (matriz[linha][coluna] == 3) {
            return setaBaixo;
        } else if (matriz[linha][coluna] == 4) {
            return setaEsquerda;
        } else if (matriz[linha][coluna] == posicao && conCarro.retornaValorSentido(2) == 2 && "Direita".equals(conCarro.getSentidoEstrada())) {
            return carroVerDireita;
        } else if (matriz[linha][coluna] == posicao && conCarro.retornaValorSentido(4) == 4 && "Esquerda".equals(conCarro.getSentidoEstrada())) {
            return carroVerEsquerda;
        }else if (matriz[linha][coluna] == posicao && conCarro.retornaValorSentido(3) == 3 && "Baixo".equals(conCarro.getSentidoEstrada())) {
            return carroVerBaixo;
        }else if (matriz[linha][coluna] == posicao && conCarro.retornaValorSentido(1) == 1 && "Cima".equals(conCarro.getSentidoEstrada())) {
            return carroVerCima;
        }

        return null;
    }

    @Override
    public void atualizarSimulador(int codCarro) {
        this.codCarro = codCarro;
        criarMapa = false;
        jTableMalha.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEncerrar;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelQtdMaxima;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JTable jTableMalha;
    private javax.swing.JTextField jTextFieldQtdMaxima;
    // End of variables declaration//GEN-END:variables
}
