/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerCriacaoMalha;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import model.MalhaViaria;
import utils.IconCelulaTabela;

/**
 *
 * @author Lucas de Liz, Matheus Maas
 */
public class SimuladorMalha extends javax.swing.JFrame {

    private MalhaViaria malhaViaria = MalhaViaria.getInstance();
    private ControllerCriacaoMalha conCriacaoMalha;
    private ImageIcon areaVerde = new ImageIcon("./imagens/areia.png");
    private ImageIcon asfalto = new ImageIcon("./imagens/asfalto.png");
   
    /**
     * Creates new form viewSimuladorMalha
     */
    public SimuladorMalha() {
        initComponents();
        conCriacaoMalha = ControllerCriacaoMalha.getInstance();
        gerarTabelaMalha(conCriacaoMalha.getMatriz(), malhaViaria.getLinha(), malhaViaria.getColuna());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonIniciar = new javax.swing.JButton();
        jButtonEncerrar = new javax.swing.JButton();
        jTextFieldQtdMaxima = new javax.swing.JTextField();
        jLabelQtdMaxima = new javax.swing.JLabel();
        jTableMalha = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(242, 242, 242));

        jButtonIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonIniciar.setText("Iniciar");

        jButtonEncerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEncerrar.setText("Encerrar");
        jButtonEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncerrarActionPerformed(evt);
            }
        });

        jLabelQtdMaxima.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelQtdMaxima.setText("Quantidade Máxima de Carros:");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabelQtdMaxima)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQtdMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonIniciar)
                .addGap(27, 27, 27)
                .addComponent(jButtonEncerrar)
                .addGap(21, 21, 21))
            .addComponent(jSeparator1)
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQtdMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQtdMaxima)
                    .addComponent(jButtonIniciar)
                    .addComponent(jButtonEncerrar))
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableMalha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableMalha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMalha.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableMalha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableMalha.setEnabled(false);
        jTableMalha.setShowHorizontalLines(false);
        jTableMalha.setShowVerticalLines(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTableMalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTableMalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(530, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonEncerrarActionPerformed

    public void gerarTabelaMalha(int[][] matriz, int linha, int coluna) {
        
        
        DefaultTableModel tipoTabela = new DefaultTableModel() {

            @Override
            public int getRowCount() {
                return malhaViaria.getLinha();
            }

            @Override
            public int getColumnCount() {
                return malhaViaria.getColuna();
            }

            @Override
            public Object getValueAt(int Filai, int colunaI) {
                try {
                    return colocarIcon(Filai, colunaI, conCriacaoMalha.getMatriz());

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.toString());
                    return null;
                }
            }
        };

        tipoTabela.setRowCount(linha);
        tipoTabela.setColumnCount(coluna);
        jTableMalha.setIntercellSpacing(new Dimension(0, 0));
        jTableMalha.setRowHeight(30);
        jTableMalha.setModel(tipoTabela);
        jTableMalha.setDefaultRenderer(Object.class, new IconCelulaTabela());
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        for (int i = 0; i < jTableMalha.getColumnModel().getColumnCount(); i++) {
            TableColumn column = jTableMalha.getColumnModel().getColumn(i);
            column.setHeaderRenderer(renderer);
            column.setPreferredWidth(30);
        }
    }
    
     public ImageIcon colocarIcon(int fila, int coluna, int matriz[][]) {
        if (matriz[fila][coluna] == 0) {
            return areaVerde;
        }// else {
            //return controleMapa.Estrada(fila, coluna);
       // }
        else if(matriz[fila][coluna] != 0){
            return asfalto;
        }
        return null;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEncerrar;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabelQtdMaxima;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableMalha;
    private javax.swing.JTextField jTextFieldQtdMaxima;
    // End of variables declaration//GEN-END:variables
}
